### ISSUE TITLE
Add a way to download spectra metadata

### ISSUE THREAD

**Issue by GabrielF98** [temuller/wiserep_api#1]
If you manually download all spectra for a supernova on wiserep, you get a text file which tells you the observation dates, redshift, phase and other important info. The file is called wisrep_spectra.csv when you download it.

I know you can get redshift with the API already but it would be good to be able to get all the info in this table in some way.

The file is linked below.
[wiserep_spectra.csv](https://github.com/temuller/wiserep_api/files/14703162/wiserep_spectra.csv)

**Comment by temuller** [comment]
Hi. I have now added this feature in version 0.1.8. A file called `downloaded_spectra_info.csv` is saved under the target's directory and contains information about the downloaded spectra. 

I'll close the issue, but feel free to open it again if you find any problems.
